cd "D:\data\"
odbc load, table("dbo.T678") noquote clear

rename T678001 DealerTIN
rename T678002 NotInUse
rename T678003 ReasonDirectEntry
rename T678004 TeamId
rename T678005 DateOfAssignment
rename T678006 TeamAssignedBy
rename T678007 DateActualNotice
rename T678008 PlaceAudit
rename T678009 DateAudit
rename T678010 NoticeGeneratedBy
rename T678011 Status
rename T678012 LastActionStatus
rename T678013 LastActionTakenBy
rename T678014 LastActionDate
rename T678015 ParentNoticeId
rename T678016 Remarks
rename T678017 Name
rename T678018 Action
rename T678019 DateReschedule


label variable DealerTIN "TIN	T678001	varchar"
label variable NotInUse "Not in Use	T678002	bigint"
label variable ReasonDirectEntry "Reason in case of Direct Entry	T678003	varchar"
label variable TeamId "Team_Id	T678004	bigint"
label variable DateOfAssignment "Actual_Date of Assign to Team	T678005	smalldatetime"
label variable TeamAssigned "By Team Assigned By	T678006	bigint"
label variable DateActualNotice "Actual_Notice_Date	T678007	smalldatatime"
label variable PlaceAudit "Place_of_auditing	T678008	int"
label variable DateAudit "Date_of_auditing with time	T678009	datetime"
label variable NoticeGeneratedBy "Notice Generated By	T678010	bigint"
label variable Status "Status	T678011	int"
label variable LastActionStatus "Last_Action_status	T678012	int"
label variable LastActionTakenBy "Last_Action_TakenBy	T678013	bigint"
label variable LastActionDate "Last_Action_Date	T678014	smalldatatime"
label variable ParentNoticeId "Parent Notice ID	T678015	bigint"
label variable Remarks "Remarks in case of re issue	T678016	varchar"
label variable Name "Name	T678017	varchar"
label variable Action "Action	T678018	int"
label variable DateReschedule "Date of rescheduling	T678019	smalldatatime"

save "form37_data_auditnotice.dta", replace

